/**
 * Sistema de Base de Conocimiento de Productos
 * Genera y mantiene información detallada de cada producto automáticamente
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export interface ProductKnowledge {
  productId: string;
  productName: string;
  category: string;
  
  // Información básica
  shortDescription: string;
  detailedDescription: string;
  
  // Características clave
  keyFeatures: string[];
  benefits: string[];
  
  // Información de venta
  targetAudience: string[];
  useCases: string[];
  commonQuestions: { question: string; answer: string }[];
  
  // Comparaciones
  similarProducts: string[];
  differentiators: string[];
  
  // Información técnica
  technicalSpecs?: Record<string, string>;
  requirements?: string[];
  
  // Metadata
  lastUpdated: Date;
  autoGenerated: boolean;
}

export class ProductKnowledgeBaseService {
  
  /**
   * Genera conocimiento automático para un producto basado en su información
   */
  static async generateKnowledge(productId: string): Promise<ProductKnowledge | null> {
    try {
      const product = await prisma.product.findUnique({
        where: { id: productId }
      });

      if (!product) return null;

      // Analizar categoría y tipo de producto
      const knowledge = await this.analyzeProduct(product);
      
      return knowledge;
    } catch (error) {
      console.error('Error generando conocimiento:', error);
      return null;
    }
  }

  /**
   * Analiza un producto y genera su base de conocimiento
   */
  private static async analyzeProduct(product: any): Promise<ProductKnowledge> {
    const category = product.category;
    const name = product.name;
    const description = product.description || '';
    const tags = product.tags ? product.tags.split(',') : [];
    const price = product.price;

    // Detectar tipo de producto
    const isMegapack = name.includes('Mega Pack');
    const isCourse = name.toLowerCase().includes('curso') || tags.includes('curso');
    const isMotorcycle = category === 'PHYSICAL' && (name.toLowerCase().includes('moto') || tags.includes('moto'));
    const isLaptop = name.toLowerCase().includes('laptop') || name.toLowerCase().includes('portátil');

    let knowledge: ProductKnowledge;

    if (isMegapack) {
      knowledge = this.generateMegapackKnowledge(product, name, description, price);
    } else if (isCourse) {
      knowledge = this.generateCourseKnowledge(product, name, description, price);
    } else if (isMotorcycle) {
      knowledge = this.generateMotorcycleKnowledge(product, name, description, price);
    } else if (isLaptop) {
      knowledge = this.generateLaptopKnowledge(product, name, description, price);
    } else {
      knowledge = this.generateGenericKnowledge(product, name, description, price);
    }

    return knowledge;
  }

  /**
   * Genera conocimiento para Megapacks
   */
  private static generateMegapackKnowledge(product: any, name: string, description: string, price: number): ProductKnowledge {
    // Extraer número del megapack
    const match = name.match(/Mega Pack (\d+)/);
    const number = match ? match[1] : '';
    
    // Extraer tema del nombre
    const theme = name.split(':')[1]?.trim() || 'Cursos Digitales';

    return {
      productId: product.id,
      productName: name,
      category: 'DIGITAL',
      
      shortDescription: `Colección completa de cursos y recursos sobre ${theme}`,
      detailedDescription: description || `El ${name} incluye una amplia colección de cursos, tutoriales, plantillas y recursos digitales sobre ${theme}. Todo el contenido es descargable y de acceso inmediato.`,
      
      keyFeatures: [
        'Acceso inmediato después del pago',
        'Contenido 100% digital descargable',
        'Múltiples cursos y recursos incluidos',
        'Sin límite de tiempo de acceso',
        'Actualizaciones incluidas',
        'Soporte por WhatsApp'
      ],
      
      benefits: [
        `Aprende ${theme} desde cero hasta nivel avanzado`,
        'Ahorra cientos de miles comprando todo junto',
        'Contenido organizado y fácil de seguir',
        'Aprende a tu propio ritmo',
        'Material de alta calidad',
        'Recursos adicionales y plantillas'
      ],
      
      targetAudience: [
        'Estudiantes que quieren aprender nuevas habilidades',
        'Profesionales buscando actualización',
        'Emprendedores digitales',
        'Personas en transición de carrera',
        'Autodidactas apasionados'
      ],
      
      useCases: [
        `Aprender ${theme} profesionalmente`,
        'Iniciar un negocio o freelance',
        'Mejorar habilidades actuales',
        'Cambiar de carrera profesional',
        'Generar ingresos adicionales'
      ],
      
      commonQuestions: [
        {
          question: '¿Cómo recibo el megapack después de pagar?',
          answer: 'Inmediatamente después de confirmar tu pago, recibirás por WhatsApp el enlace de descarga con todo el contenido organizado.'
        },
        {
          question: '¿Cuánto contenido incluye?',
          answer: `El ${name} incluye múltiples cursos completos, tutoriales en video, PDFs, plantillas y recursos adicionales. Todo sobre ${theme}.`
        },
        {
          question: '¿Necesito conocimientos previos?',
          answer: 'No, el contenido está diseñado desde nivel básico hasta avanzado, perfecto para principiantes y profesionales.'
        },
        {
          question: '¿Tiene garantía?',
          answer: 'Sí, si el contenido no cumple tus expectativas, te devolvemos tu dinero en las primeras 24 horas.'
        },
        {
          question: '¿Puedo ver una muestra antes de comprar?',
          answer: 'Claro, puedo enviarte capturas del contenido incluido y el índice completo de cursos.'
        }
      ],
      
      similarProducts: [
        'Mega Pack PREMIUM (todos los 40 megapacks)',
        'Otros megapacks relacionados con ' + theme
      ],
      
      differentiators: [
        `Precio especial de solo $${price.toLocaleString('es-CO')} COP`,
        'Contenido actualizado y de calidad verificada',
        'Entrega inmediata por WhatsApp',
        'Soporte personalizado incluido'
      ],
      
      lastUpdated: new Date(),
      autoGenerated: true
    };
  }

  /**
   * Genera conocimiento para Cursos individuales
   */
  private static generateCourseKnowledge(product: any, name: string, description: string, price: number): ProductKnowledge {
    const courseTopic = name.replace(/Curso (Completo )?de /i, '').trim();

    return {
      productId: product.id,
      productName: name,
      category: 'DIGITAL',
      
      shortDescription: `Curso completo de ${courseTopic} con acceso de por vida`,
      detailedDescription: description || `Aprende ${courseTopic} desde cero con nuestro curso completo. Incluye videos, material descargable y soporte personalizado.`,
      
      keyFeatures: [
        'Videos HD con explicaciones paso a paso',
        'Material descargable (PDFs, plantillas)',
        'Acceso de por vida sin límite de tiempo',
        'Material profesional',
        'Soporte por WhatsApp',
        'Actualizaciones gratuitas'
      ],
      
      benefits: [
        `Domina ${courseTopic} profesionalmente`,
        'Aprende a tu propio ritmo',
        'Contenido práctico y aplicable',
        'Ahorra en cursos presenciales costosos',
        'Acceso desde cualquier dispositivo'
      ],
      
      targetAudience: [
        'Principiantes sin experiencia previa',
        'Personas buscando nueva habilidad',
        'Profesionales en actualización',
        'Estudiantes complementando estudios'
      ],
      
      useCases: [
        `Aprender ${courseTopic} desde cero`,
        'Mejorar habilidades profesionales',
        'Iniciar un hobby o pasatiempo',
        'Generar ingresos con nueva habilidad'
      ],
      
      commonQuestions: [
        {
          question: '¿Cuánto dura el curso?',
          answer: `El curso de ${courseTopic} incluye múltiples horas de contenido en video, pero puedes avanzar a tu propio ritmo sin límite de tiempo.`
        },
        {
          question: '¿Necesito experiencia previa?',
          answer: 'No, el curso está diseñado para principiantes y cubre desde lo básico hasta nivel avanzado.'
        },
        {
          question: '¿Incluye certificado?',
          answer: 'Son cursos de autoaprendizaje profesional diseñados para desarrollar habilidades prácticas. No incluyen certificación oficial.'
        },
        {
          question: '¿Cómo accedo al curso?',
          answer: 'Después del pago, recibes inmediatamente el enlace de acceso por WhatsApp. Puedes verlo desde cualquier dispositivo.'
        }
      ],
      
      similarProducts: [
        'Megapacks relacionados con ' + courseTopic,
        'Otros cursos complementarios'
      ],
      
      differentiators: [
        `Precio accesible de $${price.toLocaleString('es-CO')} COP`,
        'Contenido actualizado 2024-2025',
        'Soporte personalizado incluido',
        'Acceso inmediato'
      ],
      
      lastUpdated: new Date(),
      autoGenerated: true
    };
  }

  /**
   * Genera conocimiento para Motos
   */
  private static generateMotorcycleKnowledge(product: any, name: string, description: string, price: number): ProductKnowledge {
    // Extraer información de la descripción
    const yearMatch = description.match(/Modelo:?\s*(\d{4})/i) || description.match(/(\d{4})/);
    const year = yearMatch ? yearMatch[1] : 'reciente';
    
    const ccMatch = description.match(/(\d+)cc/i);
    const cc = ccMatch ? ccMatch[1] + 'cc' : '';

    return {
      productId: product.id,
      productName: name,
      category: 'PHYSICAL',
      
      shortDescription: `${name} - Modelo ${year}, excelente estado`,
      detailedDescription: description,
      
      keyFeatures: [
        `Modelo ${year}`,
        cc ? `Motor ${cc}` : 'Motor potente',
        'Papeles al día',
        'SOAT y Tecnomecánica vigentes',
        'Mantenimiento reciente',
        'Traspaso disponible'
      ],
      
      benefits: [
        'Moto lista para rodar inmediatamente',
        'Excelente estado mecánico',
        'Bajo consumo de combustible',
        'Perfecta para ciudad y carretera',
        'Precio negociable',
        'Facilidades de pago disponibles'
      ],
      
      targetAudience: [
        'Personas buscando transporte económico',
        'Trabajadores independientes (domicilios, mensajería)',
        'Estudiantes',
        'Personas con presupuesto ajustado'
      ],
      
      useCases: [
        'Transporte diario al trabajo o estudio',
        'Trabajo de domicilios o mensajería',
        'Paseos y viajes',
        'Ahorro en transporte público'
      ],
      
      commonQuestions: [
        {
          question: '¿Los papeles están al día?',
          answer: 'Sí, la moto tiene todos los papeles al día, SOAT vigente, Tecnomecánica y traspaso disponible.'
        },
        {
          question: '¿Puedo verla antes de comprar?',
          answer: 'Por supuesto, puedes venir a verla y probarla sin compromiso. Estamos en Cali, Centro Comercial El Diamante 2.'
        },
        {
          question: '¿El precio es negociable?',
          answer: `El precio publicado es $${price.toLocaleString('es-CO')} COP, pero podemos conversar y llegar a un acuerdo que te funcione.`
        },
        {
          question: '¿Tiene algún detalle o falla?',
          answer: 'La moto está en excelente estado, con mantenimiento reciente. Si vienes a verla, puedes revisarla completamente.'
        },
        {
          question: '¿Aceptan moto en parte de pago?',
          answer: 'Podemos evaluar tu moto como parte de pago. Cuéntame qué moto tienes y vemos opciones.'
        }
      ],
      
      similarProducts: [
        'Otras motos disponibles',
        'Motos de características similares'
      ],
      
      differentiators: [
        'Papeles 100% al día',
        'Mantenimiento reciente verificable',
        'Precio competitivo y negociable',
        'Ubicación céntrica en Cali',
        'Atención personalizada'
      ],
      
      technicalSpecs: {
        'Año': year,
        'Cilindraje': cc || 'Ver descripción',
        'Estado': 'Excelente',
        'Papeles': 'Al día',
        'SOAT': 'Vigente',
        'Tecnomecánica': 'Vigente'
      },
      
      lastUpdated: new Date(),
      autoGenerated: true
    };
  }

  /**
   * Genera conocimiento para Laptops
   */
  private static generateLaptopKnowledge(product: any, name: string, description: string, price: number): ProductKnowledge {
    return {
      productId: product.id,
      productName: name,
      category: 'PHYSICAL',
      
      shortDescription: `${name} - Ideal para trabajo y estudio`,
      detailedDescription: description,
      
      keyFeatures: [
        'Procesador de última generación',
        'Memoria RAM suficiente para multitarea',
        'Almacenamiento amplio',
        'Pantalla de calidad',
        'Batería de larga duración',
        'Sistema operativo incluido'
      ],
      
      benefits: [
        'Perfecta para trabajo remoto',
        'Ideal para estudiantes',
        'Rendimiento confiable',
        'Portátil y ligera',
        'Garantía incluida'
      ],
      
      targetAudience: [
        'Estudiantes universitarios',
        'Profesionales en trabajo remoto',
        'Diseñadores y creativos',
        'Personas buscando primera laptop'
      ],
      
      useCases: [
        'Trabajo de oficina y productividad',
        'Estudios y tareas universitarias',
        'Diseño y edición básica',
        'Navegación y entretenimiento'
      ],
      
      commonQuestions: [
        {
          question: '¿Viene con Windows instalado?',
          answer: 'Sí, la laptop viene con sistema operativo Windows original instalado y activado.'
        },
        {
          question: '¿Tiene garantía?',
          answer: 'Sí, incluye garantía del fabricante. Te damos todos los detalles al momento de la compra.'
        },
        {
          question: '¿Puedo verla funcionando?',
          answer: 'Claro, puedes venir a verla y probarla antes de decidir. Estamos en Cali.'
        },
        {
          question: '¿Aceptan tarjetas de crédito?',
          answer: 'Sí, aceptamos múltiples formas de pago: efectivo, transferencia, Nequi, Daviplata y tarjetas.'
        }
      ],
      
      similarProducts: [
        'Otras laptops disponibles',
        'Laptops de rango similar'
      ],
      
      differentiators: [
        'Precio competitivo',
        'Garantía incluida',
        'Asesoría personalizada',
        'Entrega inmediata'
      ],
      
      lastUpdated: new Date(),
      autoGenerated: true
    };
  }

  /**
   * Genera conocimiento genérico para otros productos
   */
  private static generateGenericKnowledge(product: any, name: string, description: string, price: number): ProductKnowledge {
    return {
      productId: product.id,
      productName: name,
      category: product.category,
      
      shortDescription: description.substring(0, 150) || `${name} - Producto de calidad`,
      detailedDescription: description,
      
      keyFeatures: [
        'Producto de calidad verificada',
        'Entrega rápida',
        'Soporte incluido',
        'Precio competitivo'
      ],
      
      benefits: [
        'Excelente relación calidad-precio',
        'Atención personalizada',
        'Garantía de satisfacción'
      ],
      
      targetAudience: [
        'Personas buscando este tipo de producto',
        'Clientes que valoran la calidad'
      ],
      
      useCases: [
        'Uso personal',
        'Uso profesional',
        'Regalo'
      ],
      
      commonQuestions: [
        {
          question: '¿Cómo es el proceso de compra?',
          answer: 'Es muy sencillo: confirmas tu pedido, realizas el pago y te enviamos el producto inmediatamente.'
        },
        {
          question: '¿Qué formas de pago aceptan?',
          answer: 'Aceptamos transferencia bancaria, Nequi, Daviplata, PayPal, MercadoPago y tarjetas de crédito.'
        },
        {
          question: '¿Tiene garantía?',
          answer: 'Sí, todos nuestros productos tienen garantía de satisfacción.'
        }
      ],
      
      similarProducts: [],
      differentiators: [
        `Precio de $${price.toLocaleString('es-CO')} COP`,
        'Atención personalizada',
        'Entrega rápida'
      ],
      
      lastUpdated: new Date(),
      autoGenerated: true
    };
  }

  /**
   * Obtiene el conocimiento de un producto (genera si no existe)
   */
  static async getProductKnowledge(productId: string): Promise<ProductKnowledge | null> {
    return await this.generateKnowledge(productId);
  }

  /**
   * Genera conocimiento para todos los productos
   */
  static async generateAllKnowledge(): Promise<void> {
    try {
      const products = await prisma.product.findMany({
        where: { status: 'AVAILABLE' }
      });

      console.log(`Generando conocimiento para ${products.length} productos...`);

      for (const product of products) {
        await this.generateKnowledge(product.id);
      }

      console.log('✅ Conocimiento generado para todos los productos');
    } catch (error) {
      console.error('Error generando conocimiento:', error);
    }
  }

  /**
   * Busca respuesta en la base de conocimiento
   */
  static async findAnswer(productId: string, question: string): Promise<string | null> {
    const knowledge = await this.getProductKnowledge(productId);
    if (!knowledge) return null;

    // Buscar en preguntas comunes
    const normalizedQuestion = question.toLowerCase();
    
    for (const qa of knowledge.commonQuestions) {
      if (normalizedQuestion.includes(qa.question.toLowerCase()) ||
          qa.question.toLowerCase().includes(normalizedQuestion)) {
        return qa.answer;
      }
    }

    return null;
  }
}
