/**
 * 🏷️ API PARA SUGERENCIAS DE TAGS INTELIGENTES
 * Endpoint para que los clientes obtengan sugerencias automáticas de tags
 */

import { NextRequest, NextResponse } from 'next/server';
import { ProductTagService, ProductTagSuggestion, ProductTagConfig } from '@/lib/product-tag-service';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { action, product } = body;

    if (!product || !product.name) {
      return NextResponse.json(
        { error: 'Producto requerido con al menos un nombre' },
        { status: 400 }
      );
    }

    switch (action) {
      case 'suggest':
        // Generar sugerencias de tags
        const suggestions: ProductTagSuggestion[] = ProductTagService.generateTagSuggestions(product);

        return NextResponse.json({
          success: true,
          suggestions,
          count: suggestions.length
        });

      case 'generate_config':
        // Generar configuración completa
        const config: ProductTagConfig = ProductTagService.generateProductConfig(product);

        return NextResponse.json({
          success: true,
          config
        });

      case 'validate':
        // Validar configuración existente
        if (!product.tags || !Array.isArray(product.tags)) {
          return NextResponse.json(
            { error: 'Tags requeridos para validación' },
            { status: 400 }
          );
        }

        const mockConfig: ProductTagConfig = {
          name: product.name,
          description: product.description || '',
          category: product.category || 'general',
          tags: product.tags,
          searchPriority: product.searchPriority || 5,
          autoGenerated: false
        };

        const validation = ProductTagService.validateTagConfig(mockConfig);

        return NextResponse.json({
          success: true,
          validation
        });

      case 'optimize':
        // Optimizar tags existentes
        if (!product.tags || !Array.isArray(product.tags)) {
          return NextResponse.json(
            { error: 'Tags requeridos para optimización' },
            { status: 400 }
          );
        }

        const optimizedTags = ProductTagService.optimizeTags(product.tags);

        return NextResponse.json({
          success: true,
          originalTags: product.tags,
          optimizedTags,
          improvements: optimizedTags.length - product.tags.length
        });

      default:
        return NextResponse.json(
          { error: 'Acción no válida. Use: suggest, generate_config, validate, optimize' },
          { status: 400 }
        );
    }

  } catch (error) {
    console.error('[API Tags] Error:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const action = searchParams.get('action');

    if (action === 'categories') {
      // Obtener categorías disponibles
      const categories = Object.keys(ProductTagService['CATEGORY_TEMPLATES']).map(category => ({
        id: category,
        name: category.charAt(0).toUpperCase() + category.slice(1),
        description: `Categoría para productos de ${category}`,
        commonTags: ProductTagService['CATEGORY_TEMPLATES'][category as keyof typeof ProductTagService['CATEGORY_TEMPLATES']].tags,
        searchTerms: ProductTagService['CATEGORY_TEMPLATES'][category as keyof typeof ProductTagService['CATEGORY_TEMPLATES']].searchTerms
      }));

      return NextResponse.json({
        success: true,
        categories
      });
    }

    if (action === 'stats') {
      // Obtener estadísticas (esto requeriría acceso a la base de datos)
      // Por ahora retornamos datos de ejemplo
      return NextResponse.json({
        success: true,
        stats: {
          totalCategories: Object.keys(ProductTagService['CATEGORY_TEMPLATES']).length,
          mostUsedTags: ['curso', 'programacion', 'marketing', 'diseno', 'musica'],
          coverage: 85,
          recommendations: [
            'Considere agregar más tags específicos a sus productos',
            'Use términos técnicos comunes en su categoría'
          ]
        }
      });
    }

    return NextResponse.json(
      { error: 'Parámetro action requerido: categories o stats' },
      { status: 400 }
    );

  } catch (error) {
    console.error('[API Tags GET] Error:', error);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}